### ISSUE TITLE
[Feature Request] Check for max pending HTLC or latest HTLC timeout of a channel

### ISSUE THREAD

**Issue by ziggie1984** [rkfg/regolancer#10]
Its very important to not fill a channel with HTLCs when the channel will shortly be resolved onchain, therefore I propose a check which either filters for the HTLC count on a channel or fetches the shortest to expiry absolute timelock and prevents more HTLC on a channel until the absolute timelock is greater than blockheight + safetyamount (20 blocks for example) again. 

I would propose some good default values and a cmd flag with which they can be modified

**Comment by rkfg** [comment]
Yes, great insight! First I thought it's not that important since if your own HTLC reached the incoming channel it'd be resolved in a few seconds and wouldn't bloat the commitment when/if it times out. But then I realized the whole operation might be a waste since we're most probably going on chain anyway and there's little reason to shift other nodes balances. The only reason for doing so that I see is to lose less total inbound liquidity (which is the most precious resource on LN) as you effectively move it to another safe channel from the dying one. But, every node is unique so it's better to have safety belts.

I have to warn you that querying this information might be slow and can't really be cached (speed is our priority!). I suppose this situation is quite rare, maybe we can do this only on startup? And since rebalances often take hours, we can recheck once in a while.

**Comment by ziggie1984** [comment]
Ok you are making a good point, that would definitely decrease speed, I guess people can use tools like circuitbreaker which already prevents HTLCs to go beyond a specific value (also channel-specific). So maybe we keep this feature out of regolancer?

**Comment by rkfg** [comment]
Probably yeah, unless someone comes up with a convincing use case for rebalancing specifically.
