### ISSUE TITLE
Take "lost profits" from source channels into consideration for picking a route

### ISSUE THREAD

**Issue by TrezorHannes** [rkfg/regolancer#2]
Rebalance-lnd's biggest strength coming from the economical viable computation whether a source is the right source or not.
I just tried a rebalance with --pfrom and --pto, and it picked a rather expensive source, to pull a certainly cheaper target.

Aware that I can exclude the channel or the node, but is it feasible to implement the profitability computation to mark sources only if the cost + lost profit is < than the possible profit of a target?

**Comment by rkfg** [comment]
This can be added as an optional parameter, yes. I never found it useful personally because I know which channels are sinks and can simply exclude them from the sources (and they usually have less than 50% outbound). The rest rarely move themselves so their fees are more like random rewards I don't count on much. Setting zero fee on those channels doesn't help moving them at all so I just leave it small.

**Comment by rkfg** [comment]
Check if the max fee displayed is correct for you. Manually calculate the target channel future income (as `(base_fee + amount * fee_ppm) * econ_ratio`), subtract the source channel fee (as `base_fee + amount * fee_ppm`).
