### ISSUE TITLE
[Feature] Show all parameters and selected channels

### ISSUE THREAD

**Issue by ziggie1984** [rkfg/regolancer#28]
Proposed by some noderunners it would be nice to have a feature to show all channels which would be considered when using specific parameters of regolancer. 

For example show/record all potential source/target channels which would be flagged by using --pfrom 15 --pto 30.

A first idea was to use `--list` to show exactly that. One could also think of also providing a nice graphical output to the terminal (including channel gauges) in accordance with `lntop`.

**Comment by rkfg** [comment]
It'd be visually good to show those channels in two columns, the left one is for sources and the right one is for targets and maybe a pseudographical arrow above them to show the direction. It should also include information about the amount, whether it's absolute or relative and the values of them. Below we can show a list of excluded nodes with their names, probing parameters, whether rapid rebalance is enabled, fee limit, econ fee ratio etc. Since most parameters go into config, for the user it might be not obvious sometimes which ones are used in a particular session because those parameters can be overridden. Maybe it'd be better to call this option `--info` then as it's more than just list. Or add a verbosity parameter to it to show only the channels at the lowest level and more settings as the number goes up.

Proper positioning on screen isn't easy because different characters have different width and node runners love to put emojis in their aliases. It's still doable as there's a library that calculates string width in "cells" so it can be aligned nicely and long aliases can be trimmed. Another alternative is to use a full fledged TUI like gocui but it's probably an overkill.

**Comment by ziggie1984** [comment]
First solution by #37
