### ISSUE TITLE
Return value on failure

### ISSUE THREAD

**Issue by MEdGalo** [rkfg/regolancer#31]
Hi, is there a specific error code returned when regolancer fails to do a rebalance? I try to setup a simple loop script using "while [ $? -eq 0 ]", but on failure it also seems to repeat. So in case of no route for example it keeps spamming no route and saving it to the cache file.

**Comment by rkfg** [comment]
Hello, currently we only return non-zero codes in case of fatal errors. I think it'd be nice to do so if rebalance fails due to timeout or no routes! For that we need to see if `tryRebalance` returned a non-nil error with retry parameter set to false, this combination indicates that we should end the session with a non-zero return code.
