### ISSUE TITLE
add parameter to exclude channels by age 

### ISSUE THREAD

**Issue by dekdynamics** [rkfg/regolancer#51]
Hi,

This is an enhancement request to add a flag to exclude channels by their age.

Here is one possible scenario that it will help with:

An unsolicited channel is opened, and the default ppm in lnd.conf is high; like 2000ppm. This new channel will be picked up by a currently running rebalance operation using --pfrom. Even if you use profitability flags like like -r and -l, it is likely that this new channel will be used as a source, and you will rebalance at a loss.

If I could also set `--exclude-channel-age 7` ; any channel that is newer than 7 days will be excluded. This gives time to adjust the rebalancer or add manually channel excludes.

Thanks!

**Comment by rkfg** [comment]
Hmm, I don't quite understand. If it's unsolicited shouldn't the liquidity be on the peer's side? Then you can't use it as a source. If you open a channel yourself then you know about it and can add its ID to exceptions until you adjust the fee. And if you use `-l` then this high fee would prevent it from being used because no target channel's fee would be high enough to justify this loss. I get the idea but it really looks niche and I don't think it warrants adding a new flag for a use case that can be solved with the existing tools.

**Comment by dekdynamics** [comment]
Ah, I went back and made an edit which changed the meaning entirely. 

I use --pfrom and --pto at once. The new channels are used as targets, but they should be given a chance to flow naturally first. If I accidentally spend 2k ppm to refill a new channel and then it never moves outbound, I've lost a bunch of sats.

**Comment by dekdynamics** [comment]
I agree, but could you abstract the calculation?

So I specify: `--exclude-channel-age <days>`

and you multiply by 144?

**Comment by ziggie1984** [comment]
Cool Feature Request, agree with the approach @rkfg is proposing here

**Comment by ziggie1984** [comment]
is this feature request still free to work on ?

**Comment by rkfg** [comment]
Fixed in #52
